---
- name: This creates a user on a system
  hosts: tag_amfamtest
  become: yes
  vars:
    my_users:
      - pete
  tasks:
    - name: Create the users needed to be on the system
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
      with_items: "{{ my_users }}"
    - name: Create the default users directories
      file:
        name: "/home/{{ item }}/bin"
        state: directory
        mode: 0700
...
