 name: This will set up the user Kelly on the hosts
  hosts: servers 
  tasks:
   - name: Create the user ryan
     user:
       name: ryan
       state: present
       generate_ssh_key: yes
   - name: Copys a file to Kellys Directory
     copy:
       src: junk
       dest: /home/ryan/mydata
       owner: ryan
       group: ryan
       mode: 0444
