---
- name: This is the Ansible Lab playbook example 
  hosts: tag_ansible 
  become: yes 
  tasks:
  - name: Ensure the httpd package is installed
    yum: 
       name: httpd
       state: latest
  - name: Ensure the service http service is running
    service:
       name: httpd
       enabled: true 
       state: started
    when: webtext is defined
  - name: Ensure the firewall is allowing port 80 (Firewalld)
    firewalld:
       service: http
       permanent: true
       state: enabled
       immediate: true
    when:  ansible_distribution_major_version == "7"
  - name: Ensure the firewall is allowing port 80 (IPTables)
    command: iptables -A INPUT -p tcp --dport 80 --jump ACCEPT
    when:  ansible_distribution_major_version == "6"
  - name: Ensure the Hennessy default index.html file is in place
    template:
       src: index.j2 
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 644
    notify: restart apache
  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
